project_id = "imewkweatgvqledptdna"

[functions]
  [functions.auth-email-hook]
    verify_jwt = false
  [functions.process-email-queue]
    verify_jwt = true
  [functions.import-pricing]
    verify_jwt = false
  [functions.peek-csv]
    verify_jwt = false
  [functions.peek-json]
    verify_jwt = false
  [functions.seed-labcorp]
    verify_jwt = false
  [functions.seed-rxvalet]
    verify_jwt = false
  [functions.send-transactional-email]
    verify_jwt = true
  [functions.preview-transactional-email]
    verify_jwt = false
  [functions.handle-email-unsubscribe]
    verify_jwt = false
  [functions.handle-email-suppression]
    verify_jwt = false
  [functions.check-expiring-certifications]
    verify_jwt = false
  [functions.sync-timeoff-calendar]
    verify_jwt = true
